//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 13/10/2017 16:32:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Model
{
    public partial class Assoc_usua_consu {

        public Assoc_usua_consu()
        {
            OnCreated();
        }

        public virtual long ID
        {
            get;
            set;
        }

        public virtual System.DateTime DT_CRIACAO
        {
            get;
            set;
        }

        public virtual long Tipo_AssociacaoID
        {
            get;
            set;
        }

        public virtual long UsuarioID
        {
            get;
            set;
        }

        public virtual long ConsultaID
        {
            get;
            set;
        }

        public Tipo_Associacao Tipo_Associacao
        {
            get;
            set;
        }

        public Usuario Usuario
        {
            get;
            set;
        }

        public Consulta Consulta
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
