//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22/10/2017 18:15:42
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Entidade
{
    public partial class Atualiza {

        public Atualiza()
        {
            OnCreated();
        }

        public virtual long ID
        {
            get;
            set;
        }

        public virtual System.DateTime DT_ATUALIZACAO
        {
            get;
            set;
        }

        public virtual string DESCRICAO
        {
            get;
            set;
        }

        public virtual long ConsultaID
        {
            get;
            set;
        }

        public virtual long UsuarioID
        {
            get;
            set;
        }

        public Consulta AtualizaConsulta
        {
            get;
            set;
        }

        public Usuario Usuario
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
