//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 13/10/2017 16:32:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Model
{
    public partial class Tipo_Parametro {

        public Tipo_Parametro()
        {
            this.PARAMETRO_CONSULTAs = new List<PARAMETRO_CONSULTA>();
            OnCreated();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual long ID
        {
            get;
            set;
        }

        public virtual string NOME
        {
            get;
            set;
        }

        public virtual IList<PARAMETRO_CONSULTA> PARAMETRO_CONSULTAs
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
