//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 13/10/2017 16:32:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Model
{
    public partial class Versao {

        public Versao()
        {
            this.SQL_LINHAs = new List<SQL_LINHA>();
            this.PARAMETRO_CONSULTAs = new List<PARAMETRO_CONSULTA>();
            OnCreated();
        }

        public virtual long ID
        {
            get;
            set;
        }

        public virtual short NU_VERSAO
        {
            get;
            set;
        }

        public virtual System.DateTime DT_CRIACAO
        {
            get;
            set;
        }

        public virtual string DESCRICAO
        {
            get;
            set;
        }

        public virtual long ConsultaID
        {
            get;
            set;
        }

        public Consulta Consulta
        {
            get;
            set;
        }

        public virtual IList<SQL_LINHA> SQL_LINHAs
        {
            get;
            set;
        }

        public virtual IList<PARAMETRO_CONSULTA> PARAMETRO_CONSULTAs
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
